# Generated by Django 4.2.4 on 2023-08-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bank',
            new_name='Bank',
        ),
    ]
